### ISSUE TITLE
TypeError: _show_no_gui() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by Event-Horizon-Labs** [pyblish/pyblish-nuke#43]
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\jose.enriquez\packages\nuke_pyblish\999.0.0.dev\site-packages\pyblish_nuke\lib.py", line 70, in show
    window = (_discover_gui() or _show_no_gui)(parent)
TypeError: _show_no_gui() takes 0 positional arguments but 1 was given`

I am having the error above with the latest version, Nuke 13.0v8

**Comment by mottosso** [comment]
Looks like a bug, if you add a `parent` argument here to show_no_gui and submit a PR this can be fixed.

https://github.com/pyblish/pyblish-nuke/blob/986deae1199461174b6e1e854db1f51d15b8251f/pyblish_nuke/lib.py#L228

**Comment by Pixel-Minions** [comment]
Great! Thank you @mottosso
