### ISSUE TITLE
error with the silent non-GUI publish

### ISSUE THREAD

**Issue by srikanthpotipi** [pyblish/pyblish-nuke#44]
I see an error when I try to run File --> Publish
But the UI launches fine (File --> Publish...)

Nuke 14 

Is anyone else facing the issue? Looks like the issue is with the callback

```python
Traceback (most recent call last):
  File "D:\bot_vfx\pipe-20\.venv\Lib\site-packages\pyblish\lib.py", line 273, in emit
    callback(**kwargs)
  File "D:\bot_vfx\pipe-20\.venv\Lib\site-packages\pyblish_nuke\lib.py", line 195, in on_published
    for r in context.data["results"]:
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by mottosso** [comment]
Thanks for reporting this, help to solve it is most welcome, here's the line at the time of this issue.

https://github.com/pyblish/pyblish-nuke/blob/986deae1199461174b6e1e854db1f51d15b8251f/pyblish_nuke/lib.py#L194-L197

**Comment by srikanthpotipi** [comment]
@mottosso 
Thanks for responding. 

I tried to fix this by adding a check if `context`  exists. It works with that. But ideally the context shouldn't be empty. Curious on the internals of this

But I am trying to understand more about Pyblish and how callbacks work, data sharing, etc. Any links would be really appreciated

**Comment by mottosso** [comment]
Yes, the context should not be empty. In theory it couldn't be, as without a context there can't be any publishing. So this is a bug somewhere.

Here's the documentation.

- https://api.pyblish.com/data/events

If we follow the breadcrums:

1. Nuke calls `util.publish_iter()`: https://github.com/pyblish/pyblish-nuke/blob/986deae1199461174b6e1e854db1f51d15b8251f/pyblish_nuke/lib.py#L222
1. Which then calls [`api.emit("published", context=context)`](https://github.com/pyblish/pyblish-base/blob/7e43e5663572a6d9a23ab9d6993c1708094cc5f8/pyblish/util.py#L93)
1. Which finally calls the provided callback `def on_published(context)`: https://github.com/pyblish/pyblish-nuke/blob/986deae1199461174b6e1e854db1f51d15b8251f/pyblish_nuke/lib.py#L185

Only the problem is, no context is given from Nuke. So the solution seems to be to simply create a new context in Nuke, and pass that to publish_iter.

This is what is expected of `publish_iter`.

```py
def publish_iter(context=None, plugins=None, targets=None):
    # ...
    context = api.Context() if context is None else context
    plugins = api.discover() if plugins is None else plugins
```
